[global]
usernames = ["default"]
last_selected_username = "default"
auto_run_game = false
auto_run_game_delay = 1.0
last_selected_game = "Call of Duty World at War"

[games."Call of Duty World at War"]
last_selected_game_mode = "Single Player"

[games."Call of Duty Black Ops I"]
last_selected_game_mode = "Single Player"

[games."Call of Duty Black Ops II"]
last_selected_game_mode = "Multiplayer"

[games."Call of Duty Modern Warfare III"]
last_selected_game_mode = "Multiplayer"
