[global]
usernames = ["fdfsdf"]
last_selected_username = "fdfsdf"
global_args = []
last_selected_game = "Call of Duty Modern Warfare III"
auto_run_game_delay = 1.0
use_staging = false
auto_run_game = false
theme = "tokyo-night"

[games."Call of Duty World at War"]
game_args = ["ayo"]
last_selected_game_mode = "Single Player"
game_directory = ""

[games."Call of Duty Modern Warfare III"]
last_selected_game_mode = "Multiplayer"
game_args = []
game_directory = ""

[games."Call of Duty Black Ops I"]
last_selected_game_mode = "Single Player"
game_args = []
game_directory = ""
